### ISSUE TITLE
7/18(목) TODO 점검

### ISSUE THREAD

**Issue by geniuskey** [CRA7C/SSD#66]
## 기능 추가 요청 건
- [x] SSD – Erase 기능 추가
- [x] Logger 기능 추가 @winsowss 
- [x] Runner 기능 추가 @geniuskey 
- [x] SSD - Command Buffer 기능 추가
- [x] 시나리오추가시, 재빌드이슈해결 @geniuskey 
- [x] testapp에 Command Pattern 적용 @geniuskey 
- [x] SSD - Flush 구현 @gk1whd2 

## 발표 및 데모 준비
- [x] 전체 Class diagram - @jwh1308 
- [x] Sqeucen Diagram of 'read'  (Write 과 다를바 없을 것이기에 하나만) @jwh1308 
- [x] Sqeucen Diagram of 'Runner' (재빌드 이슈 포함) @geniuskey 
- [x] Sqeucen Diagram of 'Buffer' @gk1whd2 
- [x] Sqeucen Diagram of 'flush' @gk1whd2 (Buffer 와 하나의 Diagram으로 그릴 지 판단해주세요~ )
- [x] Sequence Diagram of `Logger` @winsowss 

## 평가팀(?) 수동 검증
- [ ] testshell 열어서 이것저것 시도해보기 (수동, 즉흥적) 30분 이상
  - [x] @jwh1308 
  - [ ] @geniuskey 
  - [x] @gk1whd2 
  - [x] @currycurry3030 
  - [x] @winsowss

**Comment by jwh1308** [comment]
## pylint - pyreverse(graphvis) 사용한 class diagram 산출물
### 사용한 명령어
```bash
pyreverse -o png -p SSD_CCC .\testapp\
```
**graphvis 설치해야 합니다.**
![image](https://github.com/user-attachments/assets/7f4e202a-bdf4-43ab-8272-eef4cc66c965)

**Comment by jwh1308** [comment]
### SSD class diagram
![image](https://github.com/user-attachments/assets/6889fa3d-b542-46b5-a57e-2a423ff6448a)

**Comment by jwh1308** [comment]
![image](https://github.com/user-attachments/assets/e140b59f-8c42-4596-9cca-66533637d01a)

**Comment by jwh1308** [comment]
![image](https://github.com/user-attachments/assets/e82eba8f-4621-43cf-9806-d480ebb5d89e)

**Comment by jwh1308** [comment]
### Shell App Read command
![shell_read drawio](https://github.com/user-attachments/assets/642c228f-d094-4ae6-b734-3225dce149a0)

**Comment by jwh1308** [comment]
### Shell App Erase command
![shell app erase command drawio](https://github.com/user-attachments/assets/539c3c44-41ca-49d5-917f-a47f01b54f4a)
